field: 56976fc8-b729-4b9b-bb45-d97776945165 # Building blocks
fieldLayouts:
  2c7c3c12-eb0f-4377-babd-2a9ff5816449:
    tabs:
      -
        elements:
          -
            fieldUid: aa92ff73-1331-4a95-8c86-7ffaf606fb98 # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 948ce29b-f372-417a-b739-18d5ef96b732 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7c6856c1-af18-4ef2-8577-37df6c065ded # Heading highlight
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ed8992f-6da8-4b32-8c69-6eedee3b89ef # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2b025f1-884f-4be1-8303-3316154507f8 # Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 975f0eca-1f3f-4326-b5c6-ddc980d11b85 # Rows
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ed8992f-6da8-4b32-8c69-6eedee3b89ef: # Description
    columnSuffix: ptdcqzny
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7c6856c1-af18-4ef2-8577-37df6c065ded: # Heading highlight
    columnSuffix: ogpfmzir
    contentColumnType: text
    fieldGroup: null
    handle: headingHighlight
    instructions: ''
    name: 'Heading highlight'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  948ce29b-f372-417a-b739-18d5ef96b732: # Heading
    columnSuffix: sdnumcti
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  975f0eca-1f3f-4326-b5c6-ddc980d11b85: # Rows
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: rows
    instructions: ''
    name: Rows
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 2237a77d-8f09-4d38-8caf-4521c5024206 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 15add603-12b9-4dc4-98df-a932bf9a07f6 # Column values
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_37_rows}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  aa92ff73-1331-4a95-8c86-7ffaf606fb98: # Eyebrow
    columnSuffix: vdqpfiwl
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: ''
    name: Eyebrow
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c2b025f1-884f-4be1-8303-3316154507f8: # Columns
    columnSuffix: qkhrwabi
    contentColumnType: text
    fieldGroup: null
    handle: columns
    instructions: ''
    name: Columns
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Label
                -
                  - handle
                  - label
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Highlight
                -
                  - handle
                  - highlight
                -
                  - width
                  - ''
                -
                  - type
                  - lightswitch
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: comparisonTable
name: 'Comparison table'
sortOrder: 34
