field: 56976fc8-b729-4b9b-bb45-d97776945165 # Building blocks
fieldLayouts:
  3ab079fd-ca55-4e78-b06f-c6334c16c0d6:
    tabs:
      -
        elements:
          -
            fieldUid: b98023ad-12f1-46f3-abda-f67a7400d69a # Eyebrow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 81c32a6d-384a-4902-b676-6f82d656cc1b # Slides
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  81c32a6d-384a-4902-b676-6f82d656cc1b: # Slides
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slides
    instructions: ''
    name: Slides
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - a1c392ae-4e81-4e36-bf27-16c659d9a766 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4e69d316-2d1b-4986-81ac-c00fd82bd7ed # Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3efebab6-66b2-47c1-b451-b5ee9fa74b36 # Heading highlight
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 77610db9-ee11-4a2a-adc4-5a98c1cab9bc # Lead
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - fe430a85-3bfb-4a6f-b6b3-3ead197087d7 # Include trust
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c70a62ae-1e2d-4b7f-8571-b7c625780dc5 # Primary button
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 97d15ad2-33ed-4ab4-ac4f-0e5d782e1cf3 # Secondary button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_29_slides}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  b98023ad-12f1-46f3-abda-f67a7400d69a: # Eyebrow
    columnSuffix: fwpasgit
    contentColumnType: text
    fieldGroup: null
    handle: eyebrow
    instructions: ''
    name: Eyebrow
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heroDecking
name: 'Hero decking'
sortOrder: 26
