field: 56976fc8-b729-4b9b-bb45-d97776945165 # Building blocks
fieldLayouts:
  1280d39d-ee6d-4cda-874b-99851d05cf84:
    tabs:
      -
        elements:
          -
            fieldUid: c3f27eca-6f57-4125-a33b-2d89d4c4dd44 # Slider
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c3f27eca-6f57-4125-a33b-2d89d4c4dd44: # Slider
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slider
    instructions: ''
    name: Slider
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 7edd04e1-36d9-4b2a-96ec-056d74536fd5 # Slika
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7a839f40-721f-4c05-a168-2b115857e29b # Naslov
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b7c5de39-11e7-4a6a-8f20-1f61245c8799 # Opis
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 22eb0c56-6930-4820-a5f4-de9fa9899bad # Povezava
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 44169954-262f-4410-812e-e9a871c88d4c # Naziv povezave
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_slider}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: slider
name: Slider
sortOrder: 3
