fieldLayouts:
  abd9cea3-74dd-41c8-ac95-ed57ea5912f9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 70083a40-a037-4b8b-8cb0-36c692f86ab2 # Blog info
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9647b4e4-45a4-450d-bdeb-5dc9c42484c9 # Kategorija
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 757d07c9-84fb-496b-a745-1bcad64ff844 # Blog SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: blogs
hasTitleField: false
name: Blogs
section: ba381812-4441-4394-ad5d-73f71125bb77 # Blogs
sortOrder: 1
titleFormat: '{{ blogInfo.naslov }}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
