fieldLayouts:
  9a652d62-9240-4a78-b06e-98adc385cc0e:
    tabs:
      -
        elements:
          -
            fieldUid: d0018b08-78f1-4774-b4c9-0d109dc99f9f # Example - badge
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: aabd0ce8-46b3-4024-9c42-23f6f496af73 # Example - description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55479512-70b9-4795-8983-b8069f9647eb # Example - images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 976f6cf3-1cd5-413d-b4fd-c28f2e9458c3 # Example - specs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de366bcb-5537-4935-94b2-81f703aafc37 # Example - price (m²)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6407d505-73e9-4cc5-a78e-aaf561fe48fa # Example - price (including VAT)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: true
name: Default
section: ac661d33-3dd7-4d7d-a3f6-b5329df8584f # Examples
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
