fieldLayouts:
  576508be-f6c0-4734-8717-5e927daa827c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: datoteke
hasUrls: false
name: Datoteke
settings:
  path: '@webroot/assets/uploads/files'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: null
