columnSuffix: fwcsbitz
contentColumnType: text
fieldGroup: bf345460-d5e2-4b3d-a6d9-ee2c32f0c747 # Examples
handle: exampleDescription
instructions: ''
name: 'Example - description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
