columnSuffix: null
contentColumnType: string
fieldGroup: 9865aeb4-5dfc-4359-a8e3-e876e61edf16 # Povpraševanja
handle: izbranaStoritev
instructions: ''
name: 'Izbrana storitev'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
