columnSuffix: null
contentColumnType: string
fieldGroup: 9e23dd8e-79e5-40d4-9264-8106bed610cf # Blog
handle: kategorija
instructions: ''
name: Kategorija
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:73c84352-d11b-4516-91a8-54939a4c8c9f' # Kategorija
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
