columnSuffix: iaybykff
contentColumnType: text
fieldGroup: e8bcd847-b23d-480f-b790-274c3b6afe91 # Global
handle: ksNaslov
instructions: ''
name: 'KS - Naslov'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
