columnSuffix: null
contentColumnType: text
fieldGroup: f54f6440-d1dc-4e3a-be90-b9d6f2a06914 # Common
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  description: ''
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage:
    - '1483'
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title}'
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - ' - {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: none
type: ether\seo\fields\SeoField
