columnSuffix: null
contentColumnType: string
fieldGroup: e8bcd847-b23d-480f-b790-274c3b6afe91 # Global
handle: stats
instructions: ''
name: Stats
searchable: false
settings:
  contentTable: '{{%stc_stats_1}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
