field: 7f917a85-a08b-4500-89c4-c4491c7eecbb # Mnenje stranke
fieldLayouts:
  2478380d-e763-46ef-84c9-0391ce100c18:
    tabs:
      -
        elements:
          -
            fieldUid: 0804ed7d-d3bc-4bca-bb30-c5bcb5be6a51 # Mnenje
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a558760a-0e15-4746-a1d3-d76126d46fd2 # Avtor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0804ed7d-d3bc-4bca-bb30-c5bcb5be6a51: # Mnenje
    columnSuffix: lpwlqfyf
    contentColumnType: text
    fieldGroup: null
    handle: mnenje
    instructions: ''
    name: Mnenje
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a558760a-0e15-4746-a1d3-d76126d46fd2: # Avtor
    columnSuffix: snnqngxj
    contentColumnType: text
    fieldGroup: null
    handle: avtor
    instructions: ''
    name: Avtor
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
