field: d7e96fa9-afd3-4a3f-acca-354f9b154d51 # Kontakt
fieldLayouts:
  2d5bf6dc-2441-48de-8c70-5c8d7e659db9:
    tabs:
      -
        elements:
          -
            fieldUid: 541d6f1f-6c1d-4318-b2bf-6e0a1d021227 # Slika ozadja
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 749496c6-f872-4765-a6d0-f05ed420e88b # Naslov
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24dc210e-38c4-4001-95be-c55411153807 # Podnaslov
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e7d9b29-8e4f-46a9-9ab0-3dd77631f809 # Slika mape
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c97c3d2e-90f0-4818-8eaa-97454e26d192 # Opis
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c5672212-4033-4f25-8062-4e9d57f6ef79 # Povezava
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f08fdb5b-8fe2-47af-883b-5ee2950d182d # Naziv povezave
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7e7d9b29-8e4f-46a9-9ab0-3dd77631f809: # Slika mape
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: 'Slika mape'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  24dc210e-38c4-4001-95be-c55411153807: # Podnaslov
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subTitle
    instructions: ''
    name: Podnaslov
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  541d6f1f-6c1d-4318-b2bf-6e0a1d021227: # Slika ozadja
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: backgroundImage
    instructions: ''
    name: 'Slika ozadja'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  749496c6-f872-4765-a6d0-f05ed420e88b: # Naslov
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Naslov
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c97c3d2e-90f0-4818-8eaa-97454e26d192: # Opis
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Opis
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c5672212-4033-4f25-8062-4e9d57f6ef79: # Povezava
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonUrl
    instructions: ''
    name: Povezava
    searchable: true
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  f08fdb5b-8fe2-47af-883b-5ee2950d182d: # Naziv povezave
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonTitle
    instructions: ''
    name: 'Naziv povezave'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
