field: 70083a40-a037-4b8b-8cb0-36c692f86ab2 # Blog info
fieldLayouts:
  1dbc0dd0-eb6b-437d-85ee-368b0fad5554:
    tabs:
      -
        elements:
          -
            fieldUid: c5cc323c-2030-472a-a32c-2b35e8f56c84 # Slika
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27a20311-ffa7-4a8d-8441-2099a93dbbd0 # Naslov
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6bf4087-21ef-4dbf-b249-7c2055651ed1 # Kratek povzetek
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42225258-bbf0-400e-acdc-17ab1b80727e # Besedilo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cb95f6d8-9033-439e-b025-15a125218342 # Galerija
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  27a20311-ffa7-4a8d-8441-2099a93dbbd0: # Naslov
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: naslov
    instructions: ''
    name: Naslov
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  42225258-bbf0-400e-acdc-17ab1b80727e: # Besedilo
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: besedilo
    instructions: ''
    name: Besedilo
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c5cc323c-2030-472a-a32c-2b35e8f56c84: # Slika
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: slika
    instructions: ''
    name: Slika
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c6bf4087-21ef-4dbf-b249-7c2055651ed1: # Kratek povzetek
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: kratekPovzetek
    instructions: ''
    name: 'Kratek povzetek'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cb95f6d8-9033-439e-b025-15a125218342: # Galerija
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: galerija
    instructions: ''
    name: Galerija
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:840e2501-1cc7-4112-ac2f-5ef95840022c' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
