defaultPlacement: end
enableVersioning: true
handle: examples
name: Examples
propagationMethod: all
siteSettings:
  3c3b2d8d-2be7-4175-aa7f-56aa8a6b8ac6: # INeG
    enabledByDefault: true
    hasUrls: true
    template: examples/_entry
    uriFormat: 'examples/{slug}'
type: channel
