defaultPlacement: end
enableVersioning: true
handle: leseneTerase
name: 'Lesene terase'
propagationMethod: all
siteSettings:
  3c3b2d8d-2be7-4175-aa7f-56aa8a6b8ac6: # INeG
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: lesene-terase
type: single
