defaultPlacement: end
enableVersioning: true
handle: vrtneHiskeInLope
name: 'Vrtne hiške in nadstreški'
propagationMethod: all
siteSettings:
  3c3b2d8d-2be7-4175-aa7f-56aa8a6b8ac6: # INeG
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: vrtne-hiske-in-nadstreski
type: single
